version: "3.8"
services:
  environment:
    build: .
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./flask-server:/app/flask-server

  server:
    container_name: node-server
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server

  client:
    container_name: react-client
    restart: always
    build: ./client
    volumes:
      - ./client:/app/client
    ports:
      - "3000:3000"
